[UdpInput]
address = "127.0.0.1:29329"

[JsonDecoder]
type ="JsonDecoder"
encoding_name = "JSON"

[ProtobufDecoder]
type = "ProtobufDecoder"
encoding_name = "PROTOCOL_BUFFER"

[LogOutput]
type = "LogOutput"
message_matcher = "TRUE"

[default]
type ="StatFilter"
message_matcher = "Type == \"mytype\""

[sample]
type = "StatFilter"
message_matcher = "Type == \"counter\" || Type == \"gauge\""
